set gaGui(xy) +296+239
set gaSet(iprelay)   ""
set gaSet(TestMode)    "AllTests"
set gaSet(entDUT) "ETX-220A_FTR/HN/ACR/2XFP/20S/PTP/ESK"
set gaSet(DutInitName) "ETX-220A_FTR.HN.ACR.2XFP.20S.PTP.ESK.tcl"
set gaSet(ddrRunQty)   "20"
set gaSet(ddrSOF)   "0"
set gaSet(pioType) "Ex"
set gaSet(eraseTitle) "0"
