set gaGui(xy) +335+316
set gaSet(iprelay)   ""
set gaSet(TestMode)    "AllTests"
set gaSet(entDUT) "ETX-220A_SH/ACR/3XFP/10S/SYE/ESK"
set gaSet(DutInitName) "ETX-220A_SH.ACR.3XFP.10S.SYE.ESK.tcl"
set gaSet(ddrRunQty)   "20"
set gaSet(ddrSOF)   "1"
set gaSet(pioType) "Usb"
set gaSet(eraseTitle) "0"
