set gaGui(xy) +333+728
set gaSet(iprelay)   ""
set gaSet(TestMode)    "AllTests"
set gaSet(entDUT) "ETX-220A_EIR/H/DCR/4XFP/10S/SYE/ESK"
set gaSet(DutInitName) "ETX-220A_EIR.H.DCR.4XFP.10S.SYE.ESK.tcl"
set gaSet(ddrRunQty)   "20"
set gaSet(ddrSOF)   "0"
set gaSet(pioType) "Ex"
set gaSet(eraseTitle) "0"
