set gaGui(xy) +331+274
set gaSet(iprelay)   ""
set gaSet(TestMode)    "AllTests"
set gaSet(entDUT) "ETX-220A_TMX/ACR/XPK1/3XFP/10S/SYE/ESK"
set gaSet(DutInitName) "ETX-220A_TMX.ACR.XPK1.3XFP.10S.SYE.ESK.tcl"
set gaSet(ddrRunQty)   "20"
set gaSet(ddrSOF)   "0"
set gaSet(pioType) "Ex"
set gaSet(eraseTitle) "0"
