# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded RLClose 1.0 [list source [file join $dir RLClose.tcl]]
package ifneeded RLDExPio 1.65 [list load [file join $dir RLDExPio.dll]]
package ifneeded RLDPio 2.0 [list load [file join $dir RLDPio.dll]]
package ifneeded RLDTcp 4.0 [list load [file join $dir RLDTcp.dll]]
package ifneeded RLDTime 2.0 [list load [file join $dir RLDTime.dll]]
package ifneeded RLDUsPio 1.0 [list load [file join $dir RLDUsPio.dll]]
package ifneeded RLEH 1.04 [list source [file join $dir RLEH.tcl]]
package ifneeded RLEtxGen 1.33 [list source [file join $dir RLEtxGen.tcl]]
package ifneeded RLExPio 1.65 [list source [file join $dir RLExPio.tcl]]
package ifneeded RLFile 1.12 [list source [file join $dir RLFile.tcl]]
package ifneeded RLLpt 1.0 [list source [file join $dir RLLpt.tcl]]
package ifneeded RLPio 2.0 [list source [file join $dir RLPio.tcl]]
package ifneeded RLScotty 1.2 [list source [file join $dir RLScotty.tcl]]
package ifneeded RLScreen 1.01 [list source [file join $dir RLScreen.tcl]]
package ifneeded RLSerial 1.2 [list source [file join $dir RLSerial.tcl]]
package ifneeded RLSocket 1.01 [list source [file join $dir RLSocket.tcl]]
package ifneeded RLSound 1.11 [list source [file join $dir RLSound.tcl]]
package ifneeded RLStatus 0.1 [list source [file join $dir RLStatus.tcl]]
package ifneeded RLTcp 4.0 [list source [file join $dir RLTcp.tcl]]
package ifneeded RLTime 3.0 [list source [file join $dir RLTime.tcl]]
package ifneeded RLUsbPio 1.0 [list source [file join $dir RLUsbPio.tcl]]
package ifneeded lpttcl 3.0 [list load [file join $dir lpttcl.dll]]\n[list source [file join $dir RLLpt.tcl]]
